/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ordersAndMeasurements;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import Database.DatabaseHelper;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Klexy
 */
public class NewMeasurement extends javax.swing.JFrame {

    DatabaseHelper db;
    String name;
    int SESSION_USER = 1;
    /**
     * Creates new form NewMeasurement
     */
    public NewMeasurement() throws SQLException {
        try {
            //setting the look and feel to Nimbus
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
              } catch (InstantiationException ex) {
            } catch (IllegalAccessException ex) {
            } catch (UnsupportedLookAndFeelException ex) {
            }
        //Nimus look and feel set
        initComponents();  
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        db = new DatabaseHelper();
        loadCustomers();
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadCustomers() throws SQLException{        
        String queryString = "select first_name, last_name, id from customers"
                + " except (select first_name, last_name, id from customers, measurements where"
                + " customers.id = measurements.customer_id)";
        db.setQuery(queryString);
        System.out.println(db);
        for(int i=0; i<db.numberOfRows; i++){
            
            String firstName = null;
            System.out.println(firstName);
            firstName = db.getValueAt(i, 0).toString();
            String lastName;
            lastName = db.getValueAt(i, 1).toString();
            String customer_id;
            customer_id = db.getValueAt(i, 2).toString();
            name = firstName + " " + lastName;
            System.out.printf("%s %s\n", firstName, lastName);   
            this.customerCmBox.addItem(new ComboItem(name, customer_id));
        }      
        System.out.println("Finished loading customers");
       
        Calendar cal = Calendar.getInstance(Locale.FRENCH);
        this.dateJXDatePicker.setDate(cal.getTime());
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        burstTxtFld = new javax.swing.JTextField();
        waistTxtFld = new javax.swing.JTextField();
        hipsTxtFld = new javax.swing.JTextField();
        sleeveTxtFld = new javax.swing.JTextField();
        backTxtFld = new javax.swing.JTextField();
        armTxtFld = new javax.swing.JTextField();
        chestTxtFld = new javax.swing.JTextField();
        lengthTxtFld = new javax.swing.JTextField();
        bandTxtFld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        customerCmBox = new javax.swing.JComboBox();
        dateJXDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Name:");

        jLabel3.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Burst:");

        jLabel4.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Waist:");

        jLabel5.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hips:");

        jLabel6.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sleeve:");

        jLabel7.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Back:");

        jLabel8.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Arm:");

        jLabel9.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Chest:");

        jLabel10.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Length:");

        jLabel11.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Band:");

        burstTxtFld.setToolTipText("");

        waistTxtFld.setToolTipText("");

        hipsTxtFld.setToolTipText("");

        sleeveTxtFld.setToolTipText("");

        backTxtFld.setToolTipText("");

        armTxtFld.setToolTipText("");

        chestTxtFld.setToolTipText("");

        lengthTxtFld.setToolTipText("");

        bandTxtFld.setToolTipText("");
        bandTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandTxtFldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date:");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Vani", 3, 12)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addGap(59, 59, 59)
                        .addComponent(cancelBtn))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(burstTxtFld)
                            .addComponent(waistTxtFld)
                            .addComponent(hipsTxtFld)
                            .addComponent(sleeveTxtFld)
                            .addComponent(backTxtFld)
                            .addComponent(armTxtFld)
                            .addComponent(chestTxtFld)
                            .addComponent(lengthTxtFld)
                            .addComponent(bandTxtFld)
                            .addComponent(customerCmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateJXDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerCmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(burstTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(waistTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hipsTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sleeveTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(backTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(armTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(chestTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lengthTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bandTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dateJXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(burstTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(waistTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hipsTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sleeveTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(backTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(armTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(chestTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lengthTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bandTxtFld, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cancelBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(submitBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(customerCmBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dateJXDatePicker, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bandTxtFldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //DATE FORMATTER OBJECT DEFINITION
        SimpleDateFormat formatter;
        formatter = new SimpleDateFormat("yyyy-MM-dd");
        ComboItem customer = (ComboItem) this.customerCmBox.getSelectedItem();
        
        String query = "insert into measurements values("
                + customer.getValue() + ", " + this.burstTxtFld.getText().toString() + ", "
                + this.waistTxtFld.getText().toString() + ", " + this.hipsTxtFld.getText().toString() + ", "
                + this.sleeveTxtFld.getText().toString() + ", " + this.backTxtFld.getText().toString() + ", "
                + this.armTxtFld.getText().toString() + ", " + this.chestTxtFld.getText().toString() + ", "
                + this.lengthTxtFld.getText().toString() + ", " + this.bandTxtFld.getText().toString() + ", '"
                + formatter.format(this.dateJXDatePicker.getDate()) + "')";
        
        try{
            db.setQuery(query);
            this.loadCustomers();
            JOptionPane.showMessageDialog(null, "New Measurement Recorded with success.\n"
                + "You can now use this measurement when ever,\nJust click on the view "
                    + "measurements button and\nselect the customer name"
                , "Success", JOptionPane.PLAIN_MESSAGE);            
            } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Customer already has measurement in database.\n"
                + "Please use update measurement instead to change required values"
                , "Fauilure", JOptionPane.PLAIN_MESSAGE);
                  }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            } catch (InstantiationException ex) {
            } catch (IllegalAccessException ex) {
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewMeasurement().setVisible(true);
                } catch (SQLException ex) {
                   }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField armTxtFld;
    private javax.swing.JTextField backTxtFld;
    private javax.swing.JTextField bandTxtFld;
    private javax.swing.JTextField burstTxtFld;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField chestTxtFld;
    private javax.swing.JComboBox customerCmBox;
    private org.jdesktop.swingx.JXDatePicker dateJXDatePicker;
    private javax.swing.JTextField hipsTxtFld;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lengthTxtFld;
    private javax.swing.JTextField sleeveTxtFld;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField waistTxtFld;
    // End of variables declaration//GEN-END:variables
}
