/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.khamals.reports.ui;

import com.khamals.reports.menu.sales.SummarySalesReport;
import com.khamals.reports.menu.sales.SalesByType;
import com.khamals.reports.menu.sales.StaffSalesQuery;
import com.khamals.reports.menu.sales.WeeklySalesEnquiry;
import com.khamals.reports.menu.stock.SellingPrices;
import com.khamals.reports.menu.stock.OutOfStock;
import com.khamals.reports.menu.stock.CostPrices;
import com.khamals.reports.menu.stock.ItemEnquiryRep;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MINGO LAWRENCE
 */
public class ReportsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReportsJFrame
     */
    public ReportsJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        weeklySalesMenuItem = new javax.swing.JMenuItem();
        typeOfProductMenuItem = new javax.swing.JMenuItem();
        summarySalesMenuItem = new javax.swing.JMenuItem();
        staffSalesReportsMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemsEnquiryMenuItem = new javax.swing.JMenuItem();
        stockTakeItem = new javax.swing.JMenuItem();
        quantitiesReportitem = new javax.swing.JMenuItem();
        sellingPriceItem = new javax.swing.JMenuItem();
        costPriceItem = new javax.swing.JMenuItem();
        shelfLifeItem = new javax.swing.JMenuItem();
        outOfStockItems = new javax.swing.JMenuItem();
        historyItems = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 10, 55));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Sales");

        weeklySalesMenuItem.setText("Weekly Sales  Report");
        weeklySalesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklySalesMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(weeklySalesMenuItem);

        typeOfProductMenuItem.setText("Type of Product Report");
        typeOfProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeOfProductMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(typeOfProductMenuItem);

        summarySalesMenuItem.setText("Summary of Sales Report");
        summarySalesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summarySalesMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(summarySalesMenuItem);

        staffSalesReportsMenuItem.setText("Staff  Sales  Report");
        staffSalesReportsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffSalesReportsMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(staffSalesReportsMenuItem);

        jMenuItem4.setText("Sales Analysis");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Stock");

        itemsEnquiryMenuItem.setText("Items  Enquiry Report");
        itemsEnquiryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsEnquiryMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(itemsEnquiryMenuItem);

        stockTakeItem.setText("Current Stock Take Report");
        jMenu3.add(stockTakeItem);

        quantitiesReportitem.setText("Quantitties in Stock");
        jMenu3.add(quantitiesReportitem);

        sellingPriceItem.setText("Selling Price Report");
        sellingPriceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingPriceItemActionPerformed(evt);
            }
        });
        jMenu3.add(sellingPriceItem);

        costPriceItem.setText("Cost Price Report");
        costPriceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costPriceItemActionPerformed(evt);
            }
        });
        jMenu3.add(costPriceItem);

        shelfLifeItem.setText("Slow Items (Shelf Life Report)");
        jMenu3.add(shelfLifeItem);

        outOfStockItems.setText("Out Of Stock");
        outOfStockItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outOfStockItemsActionPerformed(evt);
            }
        });
        jMenu3.add(outOfStockItems);

        historyItems.setText("Item's  History");
        jMenu3.add(historyItems);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("POS");

        jMenuItem1.setText("Group Sales");
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void weeklySalesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklySalesMenuItemActionPerformed

        try {
            WeeklySalesEnquiry hsQd = new WeeklySalesEnquiry(this, rootPaneCheckingEnabled);
            hsQd.setTitle("Weekly  Sales  Report");
            hsQd.setBackground(Color.yellow);
            hsQd.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_weeklySalesMenuItemActionPerformed

    private void staffSalesReportsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffSalesReportsMenuItemActionPerformed
       
        try {
            StaffSalesQuery qd1 = new StaffSalesQuery(this, rootPaneCheckingEnabled);
            qd1.setTitle("Staff  Sales  Report");
            qd1.setBackground(Color.yellow);
            qd1.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_staffSalesReportsMenuItemActionPerformed

    private void summarySalesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summarySalesMenuItemActionPerformed
        
        try {
            SummarySalesReport summary = new SummarySalesReport(this, rootPaneCheckingEnabled);
            summary.setTitle("Summary of Sales Report");
            summary.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_summarySalesMenuItemActionPerformed

    private void typeOfProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeOfProductMenuItemActionPerformed
        
        try {
            SalesByType sales = new SalesByType(this, rootPaneCheckingEnabled);
            sales.setTitle("Sales by Product Type");
            sales.setBackground(Color.yellow);
            sales.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_typeOfProductMenuItemActionPerformed

    private void itemsEnquiryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsEnquiryMenuItemActionPerformed
        ItemEnquiryRep itemsEnquire;
        try {
            itemsEnquire = new ItemEnquiryRep(this, rootPaneCheckingEnabled);
            itemsEnquire.setTitle("Items  Enquiry  Report");
            itemsEnquire.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_itemsEnquiryMenuItemActionPerformed

    private void sellingPriceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingPriceItemActionPerformed
        SellingPrices sp = new SellingPrices(this, rootPaneCheckingEnabled);
        sp.setTitle("Selling  Prices Report");
        sp.setVisible(true);
        
    }//GEN-LAST:event_sellingPriceItemActionPerformed

    private void costPriceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costPriceItemActionPerformed
        
        try {
            CostPrices cp = new CostPrices(this, rootPaneCheckingEnabled);
            cp.setTitle("Cost  Prices  Report");
            cp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_costPriceItemActionPerformed

    private void outOfStockItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outOfStockItemsActionPerformed
        
        try {
            OutOfStock outStock = new OutOfStock(this, rootPaneCheckingEnabled);
            outStock.setTitle("Out Of Stock Report");
            outStock.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ReportsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outOfStockItemsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 this.toFront();
     this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
     this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReportsJFrame homeReports = new ReportsJFrame();
                homeReports.setBackground(Color.yellow);
                homeReports.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem costPriceItem;
    private javax.swing.JMenuItem historyItems;
    private javax.swing.JMenuItem itemsEnquiryMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem outOfStockItems;
    private javax.swing.JMenuItem quantitiesReportitem;
    private javax.swing.JMenuItem sellingPriceItem;
    private javax.swing.JMenuItem shelfLifeItem;
    private javax.swing.JMenuItem staffSalesReportsMenuItem;
    private javax.swing.JMenuItem stockTakeItem;
    private javax.swing.JMenuItem summarySalesMenuItem;
    private javax.swing.JMenuItem typeOfProductMenuItem;
    private javax.swing.JMenuItem weeklySalesMenuItem;
    // End of variables declaration//GEN-END:variables
}
